feat: add mesif
joshualiangxy/Cache-Coherence-Simulator pull request #3
Opened 2022-11-04 07:19 UTC by KishenKumarrrrr

2022-11-04 12:35 UTC, KishenKumarrrrr commented on MESIFCacheSet.cpp
> +        case CacheLineState::FORWARD:
This should be before `CacheLineState::SHARED` ?

2022-11-04 13:46 UTC, KishenKumarrrrr commented on MESIFCacheSet.cpp
> +                numCycles += this->numCyclesToSendBlock;
Should follow similar condition as `read` case.

2022-11-04 22:01 UTC, joshualiangxy requested changes

2022-11-04 22:01 UTC, joshualiangxy commented on execute.sh
> +        ./coherence MESIF $benchmark $i 2 32 >> $benchmark-cachesize-MESIF;
```suggestion
        ./coherence MESIF $benchmark $i 2 32 >> logs/$benchmark-cachesize-MESIF;
```

2022-11-04 22:01 UTC, joshualiangxy commented on execute.sh
> +        ./coherence MESIF $benchmark $i 2 32 >> $benchmark-cachesize-MESIF;
Since the `logs/` directory is already ignored in `.gitignore`.

I suggest moving the `*-MESIF` files into there as well, so we don't commit them.

2022-11-04 22:01 UTC, joshualiangxy commented on MESICacheSet.cpp
> +        case CacheLineState::SHARED:
Merge main into your branch.

This file should not have updates.

2022-11-05 08:05 UTC, joshualiangxy requested changes

2022-11-05 08:05 UTC, joshualiangxy commented on MESIFCacheSet.cpp
> +            if(isExclusive) {
nit:

```suggestion
            if (isExclusive) {
```

2022-11-05 08:05 UTC, joshualiangxy commented on MESIFCacheSet.cpp
> +    switch(node->state) {
nit:

```suggestion
    switch (node->state) {
```

2022-11-05 08:05 UTC, joshualiangxy commented on MESIFCacheSet.cpp
> +    switch(node->state) {
nit:

```suggestion
    switch (node->state) {
```

2022-11-05 08:05 UTC, joshualiangxy commented on MESIFCacheSet.cpp
> +    switch(node->state) {
nit:

```suggestion
    switch (node->state) {
```

2022-11-05 08:05 UTC, joshualiangxy commented on MESIFCacheSet.cpp
> +            break;
nit (more explicit that shared state doesn't change):

```suggestion
        case CacheLineState::FORWARD:
        case CacheLineState::EXCLUSIVE:
        case CacheLineState::MODIFIED:
            logger->incrementBusTraffic();
            logger->addExecutionCycles(this->numCyclesToSendBlock);
            logger->addIdleCycles(this->numCyclesToSendBlock);
            node->state = CacheLineState::SHARED;
        // In MESIF, cache-to-cache sharing never happens from SHARED state.
        case CacheLineState::SHARED:
            break;
```

2022-11-06 15:37 UTC, joshualiangxy approved these changes
lgtm

2022-11-06 15:37 UTC, merged